sudo: false
language: ruby
rvm:
  - 2.5
  - 2.3
  - 2.2
before_install: gem install bundler -v 1.16.1
before_script:
  - pip install --user Flask
  - ./JSON-Schema-Test-Suite/bin/jsonschema_suite serve &
