sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
python:
  - 3.7
before_install: gem install bundler -v 1.16.1
before_script:
  - pip3 install --user Flask
  - ./JSON-Schema-Test-Suite/bin/jsonschema_suite serve &
