name: ci
on: [push, pull_request]
jobs:
  ruby:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, truffleruby-head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: |
        bundle install
        bundle exec rake test
